#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
jupyter nbconvert \
	--to 'html' \
	--ExecutePreprocessor.allow_errors=True \
	--ExecutePreprocessor.timeout=-1 \
	--FilesWriter.build_directory=../results \
	--execute HAN_AoS3.ipynb

# The previous version of this file was commented-out and follows below:
#
# jupyter nbconvert \
# 	--to 'html' \
# 	--ExecutePreprocessor.allow_errors=True \
# 	--ExecutePreprocessor.timeout=-1 \
# 	--FilesWriter.build_directory=../results \
# 	--execute HAN_AoS3.ipynb
# 
# # The previous version of this file was commented-out and follows below:
# #
# # jupyter nbconvert \
# # 	--to 'html' \
# # 	--ExecutePreprocessor.allow_errors=True \
# # 	--ExecutePreprocessor.timeout=-1 \
# # 	--FilesWriter.build_directory=../results \
# # 	--execute HAN_AoS3.ipynb
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # #!/usr/bin/env bash
# # # set -ex
# # # pip install --upgrade jinja2
# # # # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# # # jupyter nbconvert \
# # # 	--to 'html' \
# # # 	--ExecutePreprocessor.allow_errors=True \
# # # 	--ExecutePreprocessor.timeout=-1 \
# # # 	--FilesWriter.build_directory=../results \
# # # 	--execute HAN_AoS3.ipynb
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # python -u HAN_AoS3.py "$@"
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # jupyter nbconvert \
# # # # # 	--to 'html' \
# # # # # 	--ExecutePreprocessor.allow_errors=True \
# # # # # 	--ExecutePreprocessor.timeout=-1 \
# # # # # 	--FilesWriter.build_directory=../results \
# # # # # 	--execute HAN_AoS3.ipynb
# # # # # 
# # # # 
# # # 
# # 
# 
